# Generated by Django 2.1.4 on 2019-09-04 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='burneruser',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='burneruser',
            unique_together={('identification_number', 'identification_type')},
        ),
    ]
