# Generated by Django 3.0.4 on 2020-03-19 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tech_auth', '0002_auto_20200319_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentifyingDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identification_number', models.CharField(max_length=15)),
                ('identification_type', models.CharField(choices=[('tz', 'tz'), ('ps', 'ps')], default='tz', max_length=2)),
                ('passport_country', models.CharField(default='IL', max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifying_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('identification_number', 'identification_type', 'passport_country')},
            },
        ),
    ]
