# Generated by Django 2.1.4 on 2019-09-05 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tech_auth', '0002_auto_20190904_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='burneruser',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
