# Generated by Django 2.1.4 on 2019-09-18 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tech_auth', '0003_burneruser_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('details', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
