# Generated by Django 2.2.9 on 2020-02-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_auth', '0005_auto_20200215_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='burneruser',
            name='identification_typesss',
            field=models.CharField(default='tz', max_length=15),
        ),
    ]
