# Generated by Django 2.2.9 on 2020-02-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_auth', '0006_burneruser_identification_typesss'),
    ]

    operations = [
        migrations.AddField(
            model_name='burneruser',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FR', max_length=2),
        ),
    ]
