# Generated by Django 2.2.9 on 2020-02-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_auth', '0008_auto_20200215_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='burneruser',
            name='year_in_school',
        ),
        migrations.AlterField(
            model_name='burneruser',
            name='identification_type',
            field=models.CharField(choices=[('tz', 'tz'), ('ps', 'ps')], default='tz', max_length=2),
        ),
    ]
