# Generated by Django 2.2.9 on 2020-02-17 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech_auth', '0009_auto_20200215_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='burneruser',
            name='identification_typesss',
        ),
    ]
