# Generated by Django 2.2.9 on 2020-02-22 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech_auth', '0010_remove_burneruser_identification_typesss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='burneruser',
            name='street',
        ),
    ]
